### PR TITLE
Leaf4 Template Commenting & Multiline Parameters

### LINKED ISSUE #15: comment syntax
Original comment syntax of:

```
        #("foo")
        #// this is a comment!
        bar
```

and multi-line of:

```
        #("foo")
        #/*
            this is a comment!
        */
        bar
```

not currently supported, and conflicts with our new preference of `:` to open a body and subsequent `#end<tag>` syntax.

I propose moving to:

```
#com:
  this is a comment here :)
#endcom
```

### PR DESCRIPTION
**Pull request by tdotclare**
This release adds template commenting and splitting tag parameters across lines.

### Commenting Format
* Comments can be located anywhere inside the parameters of a tag call, but not inside parameters themselves
* Comment blocks are opened and closed with the configured tagIndicator (`#` in normal/default situations)
* Comment blocks may contain any character but the tagIndicator (which may be escaped to include - `\#`)
* An anonymous tag can be used as a top-level comment, either as a single or multiline comment

Example; the following Leaf template:
```rust
#("foo" # is a stringLiteral #)

#aTag(1_000 # is a thousand #, "bar" # is also a parameter #)

#notAComment("# This is a literal string #")

#(# Anonymous tags are effectively both single line... #)

#(# 
... and multiline comments
#)
```
... is identical to:
```rust
#("foo")

#aTag(1_000, "bar")

#notAComment("# This is a literal string #")


```

### Multiline Parameters
For clarity, tag parameters may be split across lines.

Example:
```rust
#(5
  +
  5)

// is identical to

#(5 + 5)
```
And can be combined with comments:
```rust
#if(permitted(customer,   # Customer permissions #
              asset.acl   # Groups allowed #)):
    Hi #(customer.name)! You have access!
#endif
```

### Notes
This release closes #15

### CODE REVIEW

**Comment by tdotclare** [comment]
Happy to hear any opinions on this and not going to push it until I do get some opinions; personally I feel it's the best solution for Leaf to keep comments isolated to parts of the template (eg, the parameters) that can never be considered part of the underlying, resulting language's syntax.

**Comment by cweinberger** [comment]
Great work, I really miss comments in Leaf.

From what I can see the syntax looks a bit complex. I think I would prefer a simple consistent format – from my POV it doesn't even have to support inline comments. Maybe something that is close to what Swift offers.

```
#// single-line comment

#/*
multi-line comments
*/#
```

If inline comments are needed, I would try to use the multi-line comments syntax:
```
#if(true #/* always true */#) { ... }
```

**Comment by tanner0101** [comment]
+1 to @cweinberger's suggestion. One of Leaf's original design goals was to feel similar to Swift. This is also the syntax used by Vapor 3's Leaf: https://docs.vapor.codes/3.0/leaf/overview/#comments

**Comment by cweinberger** [comment]
> +1 to @cweinberger's suggestion. One of Leaf's original design goals was to feel similar to Swift. This is also the syntax used by Vapor 3's Leaf: https://docs.vapor.codes/3.0/leaf/overview/#comments

🙈 did not know we had comments in leaf-3

**Pull request closed without merging**
