### PR TITLE
Adds a new `#with()` tag to make it easier to embed and extend tags

### PR DESCRIPTION
**Pull request by pontaoski**
Adds a new `#with()` tag to make it easier to work with extend and embed tags:

```leaf
#with(parent):
  #(child)
#endwith
```

### CODE REVIEW

**Review by 0xTim — COMMENTED** [review]
Looks good on a first pass, will do a proper review when I'm at my desk

**Comment by 0xTim** [comment]
@pontaoski is this ready for review? You mentioned on Discord you were doing more work

**Comment by pontaoski** [comment]
> @pontaoski is this ready for review? You mentioned on Discord you were doing more work

Yea, this is ready for review. What I mentioned on Discord is basically me ADHDbraining and refactoring/rewriting most of Leaf's lexer and parser.

**Review by 0xTim — APPROVED** [review]
Thanks!

**Comment by 0xTim** [comment]
Original comment:

Commit One: add #with tag

This is similar to Go `text/template`'s `{{ with }}` statement, in that it
allows overriding the context for the contained block.

Commit Two: add #with sugar for extend

This allows passing a context parameter to #extend, which will cause it
to desugar into a #with around the extended content, instead of just
the extended content itself.

**Pull request merged**
